### ISSUE TITLE
with_chef_local_server isn't working with metal 0.14.2

### ISSUE THREAD

**Issue by dvlscm** [chef/chef-provisioning#159]
For context, my run environment is this:

```
chef (11.16.0.rc.0, 11.14.6, 11.14.2, 11.12.8, 11.10.4, 11.6.2)
chef-metal (0.14.2, 0.14.1)
chef-metal-fog (0.9, 0.8)
chef-zero (2.2, 2.0.2, 1.7.3)
cheffish (0.8, 0.7.1)
chefspec (4.0.2, 4.0.1)
```

When I use `with_chef_local_server` with Chef 11.16 I get this error:

```
± chef-client -z test_create.rb
Starting Chef Client, version 11.16.0.rc.0
resolving cookbooks for run list: []
Synchronizing Cookbooks:
Compiling Cookbooks...
WARN: Unresolved specs during Gem::Specification.reset:
      httpclient (>= 2.2.0.2, ~> 2.2)
      nokogiri (>= 1.4.0, ~> 1.5)
      uuidtools (~> 2.1.2)
      builder (>= 2.1.2)
      akami (~> 1.0)
      multi_json (>= 1.8.4)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.

Running handlers:
[2014-09-08T11:33:09-04:00] ERROR: Running exception handlers
Running handlers complete
[2014-09-08T11:33:09-04:00] ERROR: Exception handlers complete
[2014-09-08T11:33:09-04:00] FATAL: Stacktrace dumped to /Users/me/.chef/local-mode-cache/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 2.964702 seconds
[2014-09-08T11:33:09-04:00] ERROR: undefined method `join' for Chef::Util::PathHelper:Class
[2014-09-08T11:33:09-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

With stacktrace:

```
Generated at 2014-09-08 11:35:35 -0400
NoMethodError: undefined method `join' for Chef::Util::PathHelper:Class
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cheffish-0.8/lib/cheffish/recipe_dsl.rb:77:in `block in with_chef_local_server'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cheffish-0.8/lib/cheffish/recipe_dsl.rb:74:in `each'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cheffish-0.8/lib/cheffish/recipe_dsl.rb:74:in `with_chef_local_server'
/Users/me/Workspaces/pipefitter/test_create.rb:4:in `from_file'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.16.0.rc.0/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.16.0.rc.0/lib/chef/mixin/from_file.rb:30:in `from_file'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.16.0.rc.0/lib/chef/run_context.rb:177:in `load_recipe_file'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.16.0.rc.0/lib/chef/policy_builder/expand_node_object.rb:76:in `block in setup_run_context'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.16.0.rc.0/lib/chef/policy_builder/expand_node_object.rb:75:in `each'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.16.0.rc.0/lib/chef/policy_builder/expand_node_object.rb:75:in `setup_run_context'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.16.0.rc.0/lib/chef/client.rb:265:in `setup_run_context'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.16.0.rc.0/lib/chef/client.rb:429:in `do_run'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.16.0.rc.0/lib/chef/client.rb:213:in `block in run'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.16.0.rc.0/lib/chef/client.rb:207:in `fork'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.16.0.rc.0/lib/chef/client.rb:207:in `run'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.16.0.rc.0/lib/chef/application.rb:236:in `run_chef_client'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.16.0.rc.0/lib/chef/application/client.rb:338:in `block in run_application'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.16.0.rc.0/lib/chef/application/client.rb:327:in `loop'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.16.0.rc.0/lib/chef/application/client.rb:327:in `run_application'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.16.0.rc.0/lib/chef/application.rb:55:in `run'
/Users/me/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-11.16.0.rc.0/bin/chef-client:26:in `<top (required)>'
/Users/me/.rbenv/versions/2.1.2/bin/chef-client:23:in `load'
/Users/me/.rbenv/versions/2.1.2/bin/chef-client:23:in `<main>'
```

I confirmed that the `PathHelper` class does not have a `join` method. Cheffish 0.7.1 `recipe_dsl.rb` has this code for the `with_chef_local_server` method:

``` ruby
# Ensure all paths are given
%w(acl client cookbook container data_bag environment group node role).each do |type|
  options["#{type}_path".to_sym] ||= begin
    if options[:chef_repo_path].kind_of?(String)
      run_context.config.path_join(options[:chef_repo_path], "#{type}s")
    else
      options[:chef_repo_path].map { |path| run_context.config.path_join(path, "#{type}s")}
    end
  end
  # Work around issue in earlier versions of ChefFS where it expects strings for these
  # instead of symbols
  options["#{type}_path"] = options["#{type}_path".to_sym]
end
```

Cheffish 0.8 has this:

``` ruby
# Ensure all paths are given
%w(acl client cookbook container data_bag environment group node role).each do |type|
  options["#{type}_path"] ||= begin
    if options[:chef_repo_path].kind_of?(String)
      Chef::Util::PathHelper.join(options[:chef_repo_path], "#{type}s")
    else
      options[:chef_repo_path].map { |path| Chef::Util::PathHelper.join(path, "#{type}s")}
    end
  end
end
```

The `PathHelper` `join` method is missing, and things blow up.
