### ISSUE TITLE
undefined method `synchronize' for nil:NilClass

### ISSUE THREAD

**Issue by irvingpop** [chef/chef-provisioning#18]
After upgrading my chef-metal gem to 0.3, I get the following error when calling a machine resource (which worked OK in 0.2.1)

```
================================================================================
Error executing action `create` on resource 'machine[backend1]'
================================================================================


NoMethodError
-------------
undefined method `synchronize' for nil:NilClass


Resource Declaration:
---------------------
# In /Users/irving/.chef/local-mode-cache/cache/cookbooks/harness/recipes/private_chef_ha.rb

 42:   machine backend do
 43: 
 44:     local_provisioner_options = {
 45:       'vagrant_config' => vagrant_config
 46:     }
 47:     provisioner_options ChefMetal.enclosing_provisioner_options.merge(local_provisioner_options)
 48: 
 49:     # recipe 'private-chef::provision'
 50:     #recipe 'harness::drbd'
 51: 
 52:     action :create
 53:   end
 54: 



Compiled Resource:
------------------
# Declared in /Users/irving/.chef/local-mode-cache/cache/cookbooks/harness/recipes/private_chef_ha.rb:42:in `block in from_file'

machine("backend1") do
  action [:create]
  updated true
  updated_by_last_action true
  retries 0
  retry_delay 2
  chef_server {:chef_server_url=>"http://127.0.0.1:8900", :options=>{}}
  provisioner #<ChefMetal::Provisioner::VagrantProvisioner:0x007f88da7f15b0 @cluster_path="/Users/irving/harness_vms", @unix_convergence_strategy=#<ChefMetal::ConvergenceStrategy::InstallCached:0x007f88da48b5d8 @client_rb_path="/etc/chef/client.rb", @client_pem_path="/etc/chef/client.pem", @chef_version=nil, @prerelease=nil, @package_cache_path="/Users/irving/.chef/package_cache", @package_cache={}, @tmp_dir="/tmp", @download_lock=#<Mutex:0x007f88da652448>>>
  provisioner_options {"vagrant_options"=>{"vm.box"=>"opscode-centos-6.5", "vm.box_url"=>"http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box"}, "vagrant_config"=>"    config.vm.network \"private_network\", ip: \"33.33.33.21\"\n    config.vm.network \"private_network\", ip: \"33.33.34.5\"\n    config.vm.synced_folder \"/oc/EC/Downloads\", '/tmp/cache'\n    config.vm.provider \"virtualbox\" do |v|\n      v.customize [\n        \"modifyvm\", :id,\n        \"--name\", \"backend1\",\n        \"--memory\", \"2048\",\n        \"--cpus\", \"2\",\n        \"--nictype1\", \"virtio\",\n        \"--nictype2\", \"virtio\",\n        \"--natdnshostresolver1\", \"on\",\n        \"--usb\", \"off\",\n        \"--usbehci\", \"off\"\n      ]\n      v.customize ['createhd',\n                  '--filename', \"/Users/irving/harness_vms/backend1/disk2.vmdk\",\n                  '--size', 2 * 1024,\n                  '--format', 'VMDK']\n      v.customize ['storageattach', :id,\n                  '--storagectl', 'IDE Controller',\n                  '--port', 1,\n                  '--device', 0,\n                  '--type', 'hdd',\n                  '--medium', \"/Users/irving/harness_vms/backend1/disk2.vmdk\"]\n    end\n"}
  cookbook_name "harness"
  recipe_name "private_chef_ha"
end
```
